import headerImg from "./header.png";
import fluxImg from "./flux.png";
import stick from "./stick.svg";
import moon from "./moon.svg";
import gmail from "./gmail.svg";
import tg from "./tg.svg";
import vk from "./vk.svg";
import inst from "./inst.svg";
import whiteFlux from "./whiteFlux.png";
export { headerImg, fluxImg, stick, moon, gmail, tg, vk, inst, whiteFlux };
